"""empty message

Revision ID: 7f2968576a08
Revises: d1fbf9c37afa
Create Date: 2022-03-04 13:16:17.965311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2968576a08'
down_revision = 'd1fbf9c37afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    op.drop_table('race info')
    op.drop_table('car info')
    op.drop_table('driver info')
    op.drop_column('incident', 'repair_time_of_damage')
    op.add_column('races', sa.Column('best_lap_time', sa.Integer(), nullable=False))
    op.drop_column('races', 'lap_times')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('lap_times', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('races', 'best_lap_time')
    op.add_column('incident', sa.Column('repair_time_of_damage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('driver info',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"driver info_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='driver info_pkey')
    )
    op.create_table('car info',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"car info_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('license', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('make', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='car info_pkey')
    )
    op.create_table('race info',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"race info_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('starting_position', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ending_position', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qualifying_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('average_lap_times', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('best_lap_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='race info_pkey')
    )
    op.create_table('incidents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cars_involved', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number_of_incidents', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='incidents_pkey')
    )
    # ### end Alembic commands ###
