"""empty message

Revision ID: 8c4498945a1b
Revises: 7f2968576a08
Create Date: 2022-03-04 13:59:15.885400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4498945a1b'
down_revision = '7f2968576a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race info')
    op.drop_table('driver info')
    op.drop_table('incidents')
    op.drop_table('car info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car info',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"car info_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('license', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('make', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='car info_pkey')
    )
    op.create_table('incidents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cars_involved', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number_of_incidents', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='incidents_pkey')
    )
    op.create_table('driver info',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"driver info_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='driver info_pkey')
    )
    op.create_table('race info',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"race info_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('starting_position', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ending_position', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qualifying_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('average_lap_times', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('best_lap_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='race info_pkey')
    )
    # ### end Alembic commands ###
