"""empty message

Revision ID: d1fbf9c37afa
Revises: faf231a94e33
Create Date: 2022-03-03 15:18:43.294401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fbf9c37afa'
down_revision = 'faf231a94e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('car_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'races', 'cars', ['car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'races', type_='foreignkey')
    op.drop_column('races', 'car_id')
    # ### end Alembic commands ###
