"""empty message

Revision ID: d8222ed468be
Revises: be0053ce8972
Create Date: 2022-03-03 15:16:26.212459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8222ed468be'
down_revision = 'be0053ce8972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cars', 'drivers', ['driver_id'], ['id'])
    op.drop_column('cars', 'car_id')
    op.create_foreign_key(None, 'drivers', 'cars', ['car_id'], ['id'])
    op.drop_column('drivers', 'driver_id')
    op.alter_column('incident', 'race_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'incident', 'races', ['race_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incident', type_='foreignkey')
    op.alter_column('incident', 'race_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('drivers', sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.add_column('cars', sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cars', type_='foreignkey')
    # ### end Alembic commands ###
