"""empty message

Revision ID: faf231a94e33
Revises: d8222ed468be
Create Date: 2022-03-03 15:17:54.669404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf231a94e33'
down_revision = 'd8222ed468be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'car_id')
    op.drop_column('races', 'race_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('race_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('races', sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
